# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 0st step
        uses: actions/checkout@master
      - name: 1st step
        uses: actions/checkout@master
        with:
          repository: mvdebolskiy/GEO4902
          path: ./notebooks
      - name: check
        run: cd ./notebooks
      - name: autopy-lot 
        uses: deep5050/autopy-lot@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          check: all
          input_type: ipynb
          split_at_heading: true
          output_type: markdown
          output_dir: '../_episodes/'
      - name: cd back
        run: cd ../
      - name: workaround for permission denied problem 
        run: |
          sudo chown -R $USER:$USER .
      - name: delete notebooks
        run: rm -rf ./notebooks
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Pull request with the Convreted markdown files
          title: Convert file from .ipynb to .md 
          body: This is an auto-generated PR
          branch: main
